tpm2.0-tools: fix broken 2.1.0 archive download
GitHub archives may get re-generated randomly. Apparently that has
happened to 2.1.0.tar, because the checksum no longer matches the one
recorded in the recipe:

ERROR: tpm2.0-tools-2.1.0-r0 do_fetch: Fetcher failure for URL: 'https://github.com/01org/tpm2.0-tools/archive/2.1.0.tar.gz'. Checksum mismatch!
File: '.../downloads/2.1.0.tar.gz' has md5 checksum e566fbc43a8afe0eae14e9ca91387f0b when 115b0f10abe35dd65ce40ad8a9e6a43f was expected
File: '.../downloads/2.1.0.tar.gz' has sha256 checksum 696bc0ff1d42b013f4e8fd1ea6bccf04c63e776ef0b1d0427a29eabbc3246e7b when 01c45de006011db1cc91df11043102cc23fd0d7dda9dc4a9b6ea453bec4c4b3d was expected

Checking out from git avoids this problem. The source is now in the
usual "git" repository, i.e. there's no need to rename
anything. Because the same URL is used for checking out from master
and maintenance branches, nobranch has to be used.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>